// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiHM8-_TNsaIvKUPRCbmtySot1Qw9uuX8',
    appId: '1:375479802564:android:7201900319f42e55b90791',
    messagingSenderId: '375479802564',
    projectId: 'cloudstoragedemo-a7555',
    databaseURL: 'https://cloudstoragedemo-a7555-default-rtdb.firebaseio.com',
    storageBucket: 'cloudstoragedemo-a7555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzF0tv_a4ElNXFgx-yr_4fsrA8a4OaN6c',
    appId: '1:375479802564:ios:8ad56b764ca6d26db90791',
    messagingSenderId: '375479802564',
    projectId: 'cloudstoragedemo-a7555',
    databaseURL: 'https://cloudstoragedemo-a7555-default-rtdb.firebaseio.com',
    storageBucket: 'cloudstoragedemo-a7555.appspot.com',
    androidClientId: '375479802564-l2mj2b0a7dn4f02qdcs7lsf6pafm0cub.apps.googleusercontent.com',
    iosClientId: '375479802564-b2csmmino2gll0qhhei9letm96klr3cr.apps.googleusercontent.com',
    iosBundleId: 'com.example.googlecloudstoragedemo',
  );
}
